laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/',[HomeController::class, 'index'])->name('home');
Route::get('about',[DoctorController::class, 'index'])->name('doctors.index');
Route::get('tags/{tag}',[TagController::class, 'show'])->name('tags.show');
Route::get('contact',[ContactFormController::class, 'index'])->name('contact.index');
Route::post('contact',[ContactFormController::class, 'send'])->name('contact.send');
Route::get('terms',[HomeController::class, 'terms'])->name('terms');

Route::resource('services', ServiceController::class);
Route::post('/services/{service}/schedule',[AppointmentController::class, 'store'])->name('schedule');
Route::get('services/categories/{category}',[CategoryController::class, 'services'])->name('categories.services');

Route::resource('articles', ArticleController::class);
Route::post('articles/{article}/comments',[CommentController::class, 'store'])->name('comments.store');
Route::get('articles/categories/{category}',[CategoryController::class, 'articles'])->name('categories.articles');

laravel/resources/views/about.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="text-center m-4">
            <h1>About us</h1>
        </div>
        <div class="row align-items-center">
            <div class="col-sm">
                <p><em>Augmented Heart Clinic</em> is a place of empathy and science. We do our best to make futuristic
                medical services available to everyone. From accurate central nervous system controlled hand/arm
                prosthetics to any vaccine for the latest pandemic!</p>
                <p>Our word-class medical specialists have been hand-picked to take on procedures that are safe and up
                the newest standards.</p>

                <p><a href="{{ route('services.index') }}">Schedule an appointment</a> today, we're glad to hear what time works for
                you!</p>
            </div>
        </div>
        <div class="row" id="gallery" data-toggle="modal" data-target="#galleryModal">
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff1.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="0">
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff2.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="1">
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff3.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="2">
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff4.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="3">
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff5.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="4">
            </div>
            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                <img src="img/staff6.jpg" class="w-100" data-target="#galleryCarousel" data-slide-to="5">
            </div>
        </div>
        <div class="modal fade" id="galleryModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content bg-transparent border-0">
                        {{-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"> --}}
                        {{--     <span aria-hidden="true">&times;</span> --}}
                        {{-- </button> --}}
                    <div class="modal-body">
                        <div id="galleryCarousel" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#galleryCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#galleryCarousel" data-slide-to="1"></li>
                                <li data-target="#galleryCarousel" data-slide-to="2"></li>
                                <li data-target="#galleryCarousel" data-slide-to="3"></li>
                                <li data-target="#galleryCarousel" data-slide-to="4"></li>
                                <li data-target="#galleryCarousel" data-slide-to="5"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block img-fluid" src="img/staff1.jpg" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="img/staff2.jpg" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="img/staff3.jpg" alt="Third slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="img/staff4.jpg" alt="Fourth slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="img/staff5.jpg" alt="Fith slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="img/staff6.jpg" alt="Sixth slide">
                                </div>
                            </div>
                            <a id="previous" class="carousel-control-prev" href="#galleryCarousel" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a id="next" class="carousel-control-next" href="#galleryCarousel" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center m-4">
            <h1>Medical Staff</h1>
        </div>
        <div class="card-columns">
            @foreach ($doctors as $doctor)
                <div class="card shadow">
                    <div class="card-title text-center pt-4">
                        <img class="img-circle card-img-top shadow" src="{{ $doctor->image->path }}" alt="{{ $doctor->name }}" />
                    </div>
                    <div class="card-body text-center">
                        <h5> {{ $doctor->name }} </h5>
                        <p>Specialization {{ $doctor->specialization }} </p>
                        <p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-envelope" viewBox="0 0 16 16">
                            <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
                        </svg>
                        </p>
                        <p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-telephone" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                        </svg>
                        </p>
                        <p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-linkedin" viewBox="0 0 16 16">
                            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-twitter" viewBox="0 0 16 16">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                        </svg>
                        </p>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

laravel/resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Paul Baracci">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="/style.css">
</head>
<body>
    <main role="main" id="app" class="bg-light">
        @include('header')
        @if(session('alert'))
            <alert id="alert" class="shadow" type="{{session('alert')}}"></alert>
        @endif
        <top-scroll>Scroll</top-scroll>
        @yield('content')
        @include('footer')
    </main>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{{ mix('js/app.js') }}"></script>
<script src="https://hcaptcha.com/1/api.js" async defer></script>
</body>
</html>

laravel/resources/views/footer.blade.php
<footer>
    <nav class="navbar navbar-dark bg-dark d-flex justify-content-around">
        <a class="navbar-brand" href="/"><img src="/logo-mono.png" alt="Augmented Heart Clinic" height="100"></a>
        <ul>
            <li><a href="{{ route('services.index') }}" class="nav-link text-white">Services</a></li>
            <li><a href="{{ route('doctors.index') }}"  class="nav-link text-white">About</a></li>
            <li><a href="{{ route('articles.index') }}" class="nav-link text-white">Blog</a></li>
            <li><a href="{{ route('contact.index') }}" class="nav-link text-white">Contact</a></li>
            <li><a href="{{ route('terms') }}" class="nav-link text-white">Legal</a></li>
        </ul>
        <ul>
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-facebook" viewBox="0 0 16 16">
                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-linkedin" viewBox="0 0 16 16">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
            </svg>
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-twitter" viewBox="0 0 16 16">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
            </svg>
        </ul>
    </nav>
</footer>

laravel/resources/views/header.blade.php
<header>
    <nav class="navbar navbar-expand-lg navbar-light shadow bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topnav" aria-expanded="false" aria-label="Toggle navigation">
        <div class="navbar-toggler-icon"></div>
        </button>
        <a class="navbar-brand" href="{{ route('home') }}"><img src="/logo.png" alt="Augmented Heart Clinic" height="50px"></a>
        <div class="collapse navbar-collapse justify-content-start mx-auto" id="topnav">
            <a href="{{ route('services.index') }}" class="nav-link">Services</a>
            <a href="{{ route('doctors.index') }}" class="nav-link">About</a>
            <a href="{{ route('articles.index') }}" class="nav-link">Blog</a>
            <a href="{{ route('contact.index') }}" class="nav-link">Contact</a>
            <a href="{{ route('terms') }}" class="nav-link">Terms and conditions</a>
        </div>
        <cart></cart>
    </nav>
</header>

laravel/resources/views/index.blade.php
@extends('app')

@section('content')
    <div class='container'>
        <div id="myslide" class="carousel slide mt-3 shadow" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myslide" data-slide-to="0" class="active"></li>
                <li data-target="#myslide" data-slide-to="1"></li>
                <li data-target="#myslide" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="img-fluid" src="/img/hero1.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="img-fluid" src="/img/hero2.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="img-fluid" src="/img/hero3.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#myslide" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myslide" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="container my-4">
        <div class="row align-items-center">
            <div class="col-sm">
                <div class="text-center mb-4">
                    <h1>About us</h1>
                </div>
                <p>Our focus is empathy and innovation. We do our best to make futuristic
                    medical services available to everyone. From accurate central nervous system controlled hand/arm
                    prosthetics to any vaccine for the latest pandemic!</p>
            </div>
            <div class="col-sm">
                <div class="text-center mb-4">
                    <h1>Our process</h1>
                </div>
                <p>Augmented Heart Clinic allows you to schedule appointments with ease and speed. Access the <a
                        href="{{ route('services.index') }}">Services page</a> and set up an appointment. Once a request is submitted, our
                    team will contact you to confirm the exact time and payment method.</p>
            </div>
        </div>
    </div>
    <div>
        <div class="container text-center mb-4">
            <h1 class="mb-4">Latest services</h1>
            <div class="d-flex flex-wrap flex-lg-nowrap">
            @foreach($recentServices as $service)
                <div class="card shadow m-1 p-0">
                    <img src="{{ $service->image->path }}"  alt="Image">
                    <add-to-cart :service-object="{
                        id: {{ $service->id }},
                        title: '{{ $service->title }}',
                        price: {{ $service->price }},
                        image: '{{ $service->image->path }}'
                        }">
                    </add-to-cart>
                    <a href="{{ route('services.show', ['service' => $service->id]) }}">
                        <h3 class="font-weight-semibold">{{ $service->title }}</h3>
                    </a>
                    <p><strong>Added </strong>{{ $service->created_at->diffForHumans() }}</p>
                    <h3> ${{ $service->price }} </h3>
                    <div class="m-2">
                        @include('scheduleButton')
                    </div>
                </div>
            @endforeach
            </div>
        </div>
    </div>
    <div class="wrapper">
        <div class="text-center mb-4">
            <h1>Popular Services</h1>
        </div>
        <div class="shadow slider-container">

            <div class=" slider-track">
                @foreach ($popularServices as $service)
                    <div class="shadow slider-item card text-center align-content-start">

                        <img src="{{ $service->image->path }}" class="card-img thumbnail" alt="Image">

                        <div class="col">
                        <add-to-cart :service-object="{
                            id: {{ $service->id }},
                            title: '{{ $service->title }}',
                            price: {{ $service->price }},
                            image: '{{ $service->image->path }}'
                            }">
                        </add-to-cart>
                            <a href="{{ route('services.show', ['service' => $service->id]) }}">
                                <h3 class="font-weight-semibold">{{ $service->title }}</h3>
                            </a>
                            <p><strong>scheduled</strong> {{ $service->appointments_count }} times</p>
                        </div>
                        <div class="col ml-auto mb-2">
                            <h3> ${{ $service->price }} </h3>
                            @include('scheduleButton')
                        </div>
                    </div>
                @endforeach
            </div>
            @foreach ($popularServices as $service)
                @include('scheduleModal')
            @endforeach
        </div>
        <div class="slider-buttons text-center m-2">
            <button class="btn btn-prev">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff"
                     class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
            </button>
            <button class="btn btn-next">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff"
                     class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                </svg>
            </button>
        </div>
    </div>
    <div class="container mt-4">
        <div class="text-center">
            <h1 class="my-4">Our Sponsors</h1>
            <img class="m-2 img-fluid shadow" width="200" src="/img/tyrell-corp.jpg" alt="Sponsor1"/>
            <img class="m-2 img-fluid shadow" width="200" src="/img/sarif.jpg" alt="Sponsor2"/>
            <img class="m-2 img-fluid shadow" width="200" src="/img/ocp.jpg" alt="Sponsor3"/>
        </div>
    </div>
@endsection

laravel/resources/views/scheduleButton.blade.php
<button type="button" class="btn-sm btn-success my-1" data-target="#{{ $service->title }}" data-toggle="modal" data-content="{{ $service->title }}">Schedule Appointment</button>

laravel/resources/views/scheduleModal.blade.php
<div class="modal fade text-left" id="{{ $service->title }}" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center">Confirm your <strong>{{ $service->title }}</strong> appointment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col ">
                            <div class="shadow slider-item card text-center align-content-start">
                                <img src="{{ $service->image->path }}" class="card-img" alt="Image">
                                <div class="col">
                                    <h6 class="font-weight-semibold"> {{ $service->title }} </h6>
                                    <h3>Price ${{ $service->price }} </h3>
                                    <button type="button" class="btn btn-sm">
                                        <a href="{{ route('services.show', ['service' => $service]) }}">More details</a>
                                    </button>
                                    <hr>
                                    <h6 class="text-muted font-weight-normal">
                                        {!! Str::limit($service->description, 1530) !!}
                                    </h6>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <form class="needs-validation" method="post" action="{{ route('schedule', ['service' => $service->id]) }}" novalidate>
                                @csrf
                                <div class="input-group">
                                    <input type="hidden" id="service" name="service" value="{{ $service->title }}">
                                    <input type="hidden" id="service_id" name="service_id" value="{{ $service->id }} ">
                                </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="name" name="name"
                                         placeholder="Your full name" required min="4" max="30">
                                    </div>
                                <div class="form-group">
                                    <input type="email" id="email" name="email" class="form-control"
                                    placeholder="Email" required min="4" max="30">
                                </div>
                                <div class="form-group">
                                    <input type="tel" id="phone" name="phone" class="form-control"
                                    placeholder="Phone number" required pattern="^[0-9]{5,20}$">
                                </div>
                                <div class="form-group">
                                    <input type="text" placeholder="Desired Appointment Date" onfocus="(this.type='date')" 
                                    name="desired_date" class="form-control" required >
                                </div>
                                <div class="form-group">
                                    <input type="text" placeholder="Desired Appointment Time" onfocus="(this.type='time')" 
                                    name="desired_time" class="form-control" required/>
                                </div>
                                <div class="form-group">
                                    <textarea name="comment" id="comment" class="form-control"
                                                                          placeholder="Additional comments" required>
                                    </textarea>
                                </div>
                                <div class="form-group text-center" >
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="terms" required>
                                        <label class="form-check-label" for="terms">
                                            I agree with the <a href="{{ route('terms') }}">terms and conditions</a>
                                        </label>
                                        <div class="invalid-feedback">
                                            You must agree before submitting.
                                        </div>
                                    </div>
                                </div>
                                <div class="h-captcha text-center" data-sitekey="9c6eb30c-cf96-4956-beef-49f335ee66c2"></div>
                                <div class="modal-footer justify-content-center">
                                    <button id="schedule" type="submit" class="btn btn-success">Confirm appointment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

laravel/resources/views/tag.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h1 class="text-center m-4"> {{ $tagName->name }} </h1>
        <div class="row m-2 justify-content-center">
            @include('blog.categories')
        </div>
        @foreach($tagArticles as $article)
            @include('blog.articles')
        @endforeach
    </div>
@endsection