laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/',[HomeController::class, 'index'])->name('home');
Route::get('about',[DoctorController::class, 'index'])->name('doctors.index');
Route::get('tags/{tag}',[TagController::class, 'show'])->name('tags.show');
Route::get('contact',[ContactFormController::class, 'index'])->name('contact.index');
Route::post('contact',[ContactFormController::class, 'send'])->name('contact.send');
Route::get('terms',[HomeController::class, 'terms'])->name('terms');

Route::resource('services', ServiceController::class);
Route::post('/services/{service}/schedule',[AppointmentController::class, 'store'])->name('schedule');
Route::get('services/categories/{category}',[CategoryController::class, 'services'])->name('categories.services');

Route::resource('articles', ArticleController::class);
Route::post('articles/{article}/comments',[CommentController::class, 'store'])->name('comments.store');
Route::get('articles/categories/{category}',[CategoryController::class, 'articles'])->name('categories.articles');

laravel/resources/views/blog/articles.blade.php
<div class="shadow card flex-row mb-4">
    <img class=" article-thumbnail" src="{{ $article->image->path }}">
    <div class="card-body">
        <h3 class="mx-2"><a href="{{ route('articles.show', ['article' => $article]) }}">{{ $article->article_title }}</a></h3>
        <div class="d-lg-flex justify-content-start align-items-center">
            <div class="m-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-person" viewBox="0 0 16 16">
                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                </svg>
                {{ $article->doctor->name }}
            </div>
            <div class="m-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-clock-history" viewBox="0 0 16 16">
                    <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                    <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                    <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                </svg>
                {{ $article->created_at->diffForHumans() }} 
            </div>
            <div class="m-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-chat-right-dots" viewBox="0 0 16 16">
                    <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                    <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                </svg>
                {{ $article->comments->count() }}
            </div>
            <div class="m-2">
                <a href="{{ route('categories.articles', [ 'category' => $article->category->id ]) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-list-task" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
                        <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
                        <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
                    </svg> {{ $article->category->name }}</a>
            </div>
        </div>
        <p class="card-text mx-2 mt-2">{{ $article->article_description }}</p>
        <p class="card-text mx-2">
        @foreach($article->tags as $tag)
            <a href="{{ route('tags.show', ['tag' => $tag->id]) }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tag" viewBox="0 0 16 16">
                    <path d="M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z"/>
                    <path d="M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z"/>
                </svg>
                {{ $tag->name }}
            </a>
        @endforeach
        </p>
    </div>
</div>

laravel/resources/views/blog/categories.blade.php
<category></category>
<div id="categ-drop" class="categ-drop  p-3 shadow text-center align-items-center">
    <h3 class="text-dark">Categories</h3>
    <hr>
    @foreach($categories as $category)
        <a class="m-5" href="{{ route('categories.articles', [ 'category' => $category->id ]) }}">
            <h4> {{ $category->name }}</h4>
        </a>
    @endforeach
    <hr>
    <button class="btn" 
            onclick="document.getElementById('categ-drop').style = '-700px';">
     <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#007bff" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
    </svg> 
    </button>
</div>

laravel/resources/views/blog/category.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h1 class="text-center m-4"> {{ $categoryName->name}} ( {{ $categArticleCount }} )</h1>
        <div class="row m-2 justify-content-center">
            @include('blog.categories')
        </div>
        <div class="container">
            @foreach($categoryArticles as $article)
                @include('blog.articles')
            @endforeach
        </div>
        <div class="row justify-content-center">
            {{ $categoryArticles->links() }}
        </div>
    </div>
@endsection

laravel/resources/views/blog/commentForm.blade.php
<form class="needs-validation" method="post" action="{{ route('comments.store', ['article' => $article->id]) }}"
      novalidate>
    @csrf
    <div class="form-group">
        <input type="hidden" name="article_id" value="{{ $article->id }}"/>
        <textarea
            name="message" class="form-control {{ $errors->has('message') ? ' has-error' : '' }}"
            placeholder="Leave a comment" required min="4">
        </textarea>
        <p class="text-danger">{{ $errors->first('message') }}</p>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add comment</button>
    </div>
</form>

laravel/resources/views/blog/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h1 class="text-center m-4">Our Blog</h1>
        <div class="row m-2 justify-content-center">
            @include('blog.categories')
        </div>
        <div class="container">
            @foreach($articles as $article)
                @include('blog.articles')
            @endforeach
        </div>
        <div class="row mt-4 justify-content-center">
            {{ $articles->links() }}
        </div>
    </div>

@endsection

laravel/resources/views/blog/show.blade.php
@extends('app')

@section('content')
    <div class="container my-4">
        <div class="card row shadow mx-0">
            <img class="card-img-top" src="{{ $article->image->path }}">
            <div class ="col ">
                <h2>{{ $article->article_title }}</h2>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#007bff" class="bi bi-person" viewBox="0 0 16 16">
                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                    </svg>
                    {{ $article->doctor->name }} |
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#007bff" class="bi bi-clock-history" viewBox="0 0 16 16">
                        <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                        <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                        <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                    </svg>
                    {{ $article->created_at->diffForHumans() }}
                </p>
                <p class="card-text mb-auto">
                    <a href="{{ route('categories.articles', [ 'category' => $article->category->id ]) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#007bff" class="bi bi-list-task" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
                            <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
                            <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
                        </svg> {{ $article->category->name }}</a>
                </p>
                <p class="card-text mb-auto">
                    @foreach($article->tags as $tag)
                        <a href="{{ route('tags.show', ['tag' => $tag->id]) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-tag" viewBox="0 0 16 16">
                                <path d="M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z"/>
                                <path d="M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z"/>
                            </svg>
                            {{ $tag->name }}
                        </a>
                    @endforeach
                </p>
                <hr>
                <strong class="text-center"><p>{{ $article->article_description }}</p></strong>
                <div class="col-sm">
                    <p>{{ $article->article_content }}</p>
                </div>
            </div>
        </div>
        <h3 class="my-4">{{ $article->comments->count() }} Comments</h3>
        <div class="card shadow p-4 my-4">
            @include('blog.commentForm')
            @foreach($article->comments->sortByDesc('created_at') as $comment)
                <div class="mt-1">
                    <p><strong>{{ $comment->user->name }}</strong><strong class="font-weight-light mx-3">{{ $comment->created_at->diffForHumans() }}</strong> </p>
                    <p>{{ $comment->message }}</p>
                </div>
                <hr>
            @endforeach
        </div>
    </div>
@endsection